#!/usr/bin/env bash
# Bash script that will display information about subdomains.
subdomains_config () {
    export DOMAIN="$1"
    export SUBDOMAIN="$2"

    if [[ $SUBDOMAIN =~ ^$ ]]
    then
        host -a "www.$DOMAIN" | awk '/^www./ {print "The subdomain www is a", $4, "record and points to", $5}'
        host -a "lb-01.$DOMAIN" | awk '/^lb-01./ {print "The subdomain lb-01 is a", $4, "record and points to", $5}'
        host -a "web-01.$DOMAIN" | awk '/^web-01./ {print "The subdomain web-01 is a", $4, "record and points to", $5}'
        host -a "web-02.$DOMAIN" | awk '/^web-02./ {print "The subdomain web-02 is a", $4, "record and points to", $5}'
    else
        host -a "$SUBDOMAIN.$DOMAIN" | awk '{split($1, tkn, ".")
                                         if (ENVIRON["SUBDOMAIN"] == tkn[1])
                                             printf "The subdomain %s is a %s record and points to %s\n", tkn[1], $4, $5}'
    fi
}

if [ "A$1" != "A" ]
then
    subdomains "$1" "$2"
fi
