#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School, Here I'm :)!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
# Configures 404 error page
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
# Add new custom HTTP Header
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
