#!/usr/bin/env bash
# Fix Nginx to listen on port 80 short and sweet :)
sudo sed -i 's/listen 8080 default_server.*/ listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\].*/ listen [::]:80 default_server;/g' /etc/nginx/sites-enabled/default
pkill -o nginx
