#!/usr/bin/env bash
# Displays 'Holberton School' 10 times with while
i=0
while [ $i -ne 11 ]; do
    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    i=$((i + 1))
done
