#!/usr/bin/env bash
# Displays 'Holberton School' 10 times with while
i=1
while [ $i -ne 21 ]; do
    echo $i 
    case "$i" in  
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    i=$((i + 1))
done
