#!/usr/bin/env bash
# Displays 'Holberton School' 10 times with while
hours=0
minutes=1
while [ $hours -ne 13 ]; do
    echo "Hour: $hours"
    while [ $minutes -ne 60 ]; do
        echo $minutes
        minutes=$((minutes + 1))
    done
    minutes=1
    hours=$((hours + 1))
done
