#!/bin/bash
# Blocks all incoming traffic, except TCP ports: 22(SSH), 443(HTTPS), 80(HTTP)
sudo apt-get -y update
sudo apt-get install -y ufw
sudo ufw deny incoming
sudo ufw allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
